name: Prettier Check

on: pull_request

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Prettier Check
        uses: rutajdash/prettier-cli-action@v1.0.1
        with:
          file_pattern: '**/*.ts'
